knp_snappy:
  temporary_folder: '%kernel.cache_dir%/snappy'
  process_timeout: 30
  pdf:
    enabled:    true
    binary:     '%env(WKHTMLTOPDF_PATH)%'
    options:
      enable-local-file-access: true
      encoding: 'UTF-8'
  image:
    enabled:    true
    binary:     '%env(WKHTMLTOIMAGE_PATH)%'
    options:
      enable-local-file-access: true
      encoding: 'UTF-8'
