version: '3'

services:
  app:
    container_name: app-meteo
    build: .
    ports:
      - '8000:80'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './:/var/www/html'